name: Commit Successful

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Commit successful
      run: |
        echo Your code has been committed
