name: Commit Successful

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Commit successful
      run: |
        echo Your code has been committed
- name: Send email
  uses: dawidd6/action-send-mail@v2.2.0
