on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  email:
  runs-on: ubuntu-latest

- name: Send mail
  uses: dawidd6/action-send-mail@v2
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Pass or Fail
    # Literal body:
    body: Build of ${{github.repository}} was successful.
    # Read file contents as body:
    body: file://README.md
    to: scott.pilgrim@sevenevilexes.ca
    from: Brady Trappett # <user@example.com>
    # Optional content type (defaults to text/plain):
    content_type: text/html
